spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clms
    username: clms
    password: clms1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: false
    hibernate:
      format_sql: true
      ddl-auto: update

  springdoc:
    packages-to-scan: com.example.clms.controller
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    swagger-ui:
      path: /
      disable-swagger-default-url: true
      display-request-duration: true
      operations-sorter: alpha